### ISSUE TITLE
`npx create-react-flask "path_to_dir"` works only when proper path is given.

### ISSUE THREAD

**Issue by nkilm** [nkilm/create-react-flask#1]
```bash
npx  create-react-flask <path>
```
#### The above command does not work if the path is `.` which implies current directory. It throws an error. So modify the script inside `/bin/cli.js` to fix this error.

**Comment by sreekeshiyer** [comment]
Can work on this. Please assign this issue to me :)

**Comment by sreekeshiyer** [comment]
Hey @nkilm 
I tried out `npx create-react-flask .` on Bash and Powershell and it seemed to work fine.
Please let me know if I'm not looking for the right thing. 

Cheers.

**Comment by nkilm** [comment]
Yes it seems to be working🐒

**Comment by nkilm** [comment]
There is another issue though, related to `git`. When the npx command setup the project, it should also check if `git is already initialized or not`. 
#### If git is already initialized then remove the `git` which comes with `npx`

**Comment by sreekeshiyer** [comment]
I think we should do that regardless. Why would someone (someone using a template to work on their own project) be interested in making changes to the template itself?

I do have something in mind, will make a PR soon. 

Thanks for the response!

**Comment by nkilm** [comment]
@sreekeshiyer Alright.
